In [1]:
# Annual Air Quality Data from EPA

In [2]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import time
from pprint import pprint
pd.options.display.max_columns = 9999

In [3]:
# Import park coordinates csv file as pandas dataframe
df = pd.read_csv("park_coordinates.csv")
df["Min Lat"] = df["Latitude"] - 0.44
df["Max Lat"] = df["Latitude"] + 0.44
df["Min Lon"] = df["Longitude"] - 0.44
df["Max Lon"] = df["Longitude"] + 0.44
df = round(df, 2)
df

,Latitude,Longitude,Park,Min Lat,Max Lat,Min Lon,Max Lon
0,44.34,-68.27,Acadia National Park,43.90,44.78,-68.71,-67.83
1,-14.26,-170.68,National Park of American Samoa,-14.70,-13.82,-171.12,-170.24
2,38.73,-109.59,Arches National Park,38.29,39.17,-110.03,-109.15
3,43.86,-102.34,Badlands National Park,43.42,44.30,-102.78,-101.90
4,29.13,-103.24,Big Bend National Park,28.69,29.57,-103.68,-102.80
...,...,...,...,...,...,...,...
57,43.60,-103.42,Wind Cave National Park,43.16,44.04,-103.86,-102.98
58,61.71,-142.99,Wrangell-St. Elias National Park & Preserve,61.27,62.15,-143.43,-142.55
59,44.43,-110.59,Yellowstone National Park,43.99,44.87,-111.03,-110.15
60,37.87,-119.54,Yosemite National Park,37.43,38.31,-119.98,-119.10
61,37.30,-113.03,Zion National Park,36.86,37.74,-113.47,-112.59

In [4]:
## Annual Summary Data API call using min/max latitude/longitude

# Example: "https://aqs.epa.gov/data/api/annualData/byBox?
#email=test@aqs.api&key=test&param=44201
#&bdate=20150501&edate=20150502
#&minlat=33.3&maxlat=33.6&minlon=-87.0&maxlon=-86.7"

# url_base = "https://aqs.epa.gov/data/api/annualData/byBox?"

# payload = {"email": "kangsina@gmail.com",
#            "key": "dunheron72",
#            "param": "44201",
#            "bdate": "20190608",
#            "edate": "20190608",
#            "minlat": "-14.79",
#            "maxlat": "-13.82",
#            "minlon": "-171.12",
#            "maxlon": "-170.24"}

# r = requests.get(url_base, params=payload)
# json_r = r.json()
# json_r

In [5]:
# Air Quality Data Query

url = "https://aqs.epa.gov/data/api/annualData/byBox?email=test@aqs.api&key=test&param=44201&bdate=20150608&edate=20151020"
aq_data = []

for i in range(0, len(df)-1):
    result = requests.get(url + 
                     "&minlat=" + str(df.iat[i, 3]) + 
                     "&maxlat=" + str(df.iat[i, 4]) + 
                     "&minlon=" + str(df.iat[i, 5]) + 
                     "&maxlon=" + str(df.iat[i, 6])).json()
    if result["Data"]==[]:
        print(str(df.iloc[i, 2]) + ": No site nearby")
    else:
        aq_data.append(result)

National Park of American Samoa: No site nearby
Black Canyon of the Gunnison National Park: No site nearby
Bryce Canyon National Park: No site nearby
Capitol Reef National Park: No site nearby
Crater Lake National Park: No site nearby
Denali National Park and Preserve: No site nearby
Dry Tortugas National Park: No site nearby
Gates of the Arctic National Park and Preserve: No site nearby
Glacier Bay National Park and Preserve: No site nearby
Great Sand Dunes National Park and Preserve: No site nearby
Haleakalā: No site nearby
Hawaiʻi Volcanoes National Park: No site nearby
Isle Royale National Park: No site nearby

KeyError: 'Data'

In [ ]:
# Getting values for only "Data"

aq_data_clean = []
for d in aq_data:
    aq_data_clean += d["Data"]

In [ ]:
# Converting to Pandas dataframe

df_aq = pd.DataFrame(aq_data_clean)
df_aq

In [ ]:
sites = df_aq_clean["local_site_name"].unique()

np_sites = [e for e in list(sites) if e and "NP" in e]
np_sites